package com.example.fotolajk;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class FotoLajkApplication {

	public static void main(String[] args) {
		SpringApplication.run(FotoLajkApplication.class, args);
	}

}
